### PR TITLE
Update GmailBruterV2.py

### PR DESCRIPTION
**Pull request by Jody888111**

### CODE REVIEW

**Comment by DEMON1A** [comment]
Is that a joke or something?

**Comment by Jody888111** [comment]
> No I was trying to get into a very important gmail account.The owner of the account passed away and she has 3 daughters that are gonna end up in foster homes if I can’t get into that account to get information I need to get custody. I spent all my savings and bill money to bury her and she has the information I need in that account. I’m sorry I thought I could do it.

**Comment by DEMON1A** [comment]
Hey there, I'm sorry to hear that but all I can say is that you did misunderstand how the program works. You're using `python` inside  your machine to run the code not editing the code and create a **Pull request** with the invalid edits you created to be added into the code all users will be using

The second point here, Google support will be more helpful if have some sort of a proof of this story and I think they will be more helpful dealing with this case, It's just rare cases when brute-force can work.

I hope that will be helpful, I will lock the conversation after few days, Feel free to respond until that
PS closing this pull request since it's not real edits

Cheers

**Comment by Jody888111** [comment]
Google won’t help because her ex husband tried to get into the account and
caused it to be locked. With no interest in helping the kids.I really am
sorry I’m just in a bind and I was pulling at straws.

**Comment by DEMON1A** [comment]
It's fine, But still I can't really help with this case, Only google support can deal with such case like this, Give it a try and contact them, That's the only thing you can do right now.

**Pull request closed without merging**
